Add some error handling for scripts relying on external tools.
The following scripts were updated with a check:

 * pre-commit-perl as it uses `perl`
 * pre-commit-valid-xml as it uses `xmllint`
 * pre-commit-crlf-to-lf as it uses `dos2unix`

diff --git a/hooks/pre-commit-crlf-to-lf b/hooks/pre-commit-crlf-to-lf
--- a/hooks/pre-commit-crlf-to-lf
+++ b/hooks/pre-commit-crlf-to-lf
@@ -1,14 +1,19 @@
 #!/usr/bin/env bash
 
+command -v dos2unix >/dev/null 2>&1 || {
+  echo >&2 "I require 'dos2unix' but it's not installed.  Skipping .."; exit 0;
+}
+
+
 git diff --cached --name-only | while read FILE; do
-if [[ "$FILE" =~ ^.+(java|txt|properties|pl)$ ]]; then
-    if [[ -f $FILE ]]; then
-        dos2unix $FILE
-        if [ $? -ne 0 ]; then
-            echo -e "\n\nWARNING: Aborting commit due error by executing command dos2unix with exit status [$?]. Fix them before committing.\n\n" >&2
-            exit 1
-        fi
-	git add $FILE
-    fi
-fi
+  if [[ "$FILE" =~ ^.+(java|txt|properties|pl)$ ]]; then
+      if [[ -f $FILE ]]; then
+          dos2unix $FILE
+          if [ $? -ne 0 ]; then
+              echo -e "\n\nWARNING: Aborting commit due error by executing command dos2unix with exit status [$?]. Fix them before committing.\n\n" >&2
+              exit 1
+          fi
+  	git add $FILE
+      fi
+  fi
 done || exit $?
